### PR TITLE
fix

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by alokmenghrajani** [comment]
Nice, thanks a lot!

**Comment by PascalSchumacher** [comment]
You are welcome!

**Comment by alokmenghrajani** [comment]
Any idea how to scope test dependencies (e.g. assertj) in a way that checkbugs will find them?

If I add `<scope>test</scope>` to org.assertj, I get `The following classes needed for analysis were missing: org.assertj.core.api.Assertions`.

**Comment by PascalSchumacher** [comment]
Works for me, but only with a newer maven-findbugs-plugin version, see: https://github.com/alokmenghrajani/assertj-test/pull/2

**Pull request merged**
